### PR TITLE
Eo/add create repo grep

### PR DESCRIPTION
**Pull request by eochoa260**
Was able to create, get, and export a repo grep check.

### CODE REVIEW

**Review by rocktavious — APPROVED** [review]
Did you test export works on Circular's Repo Grep?  If so then LGTM!

**Comment by rocktavious** [comment]
There appears to be a bug - when i test this out on circular with a repo grep check it doesn't print out the fields in JSON output but it does work in YAML output.  🤔

**Comment by eochoa260** [comment]
> There appears to be a bug - when i test out `get check XXX` on circular with a repo grep check it doesn't print out the fields in JSON output but it does work in YAML output. 🤔

Just now seeing this but I'll look into it and see if I can figure out what's going on.  I only tested YAML output before.

**Comment by eochoa260** [comment]
> > There appears to be a bug - when i test out `get check XXX` on circular with a repo grep check it doesn't print out the fields in JSON output but it does work in YAML output. 🤔
> 
> Just now seeing this but I'll look into it and see if I can figure out what's going on. I only tested YAML output before.

Looks like it was broken for other check types too.  Seems like running it through marshalCheck fixed it:
```
$ go run main.go get check Z2lkOi8vb3BzbGV2ZWwvQ2hlY2tzOjpSZXBvR3JlcC8xODQy
{
  "Version": "1",
  "Kind": "repo_grep",
  "Spec": {
    "category": "performance",
    "directorySearch": false,
    "enabled": true,
    "fileContentsPredicate": {
      "Type": "exists",
      "Value": ""
    },
    "filePaths": [
      "**/go.mod"
    ],
    "filter": "test-filter",
    "level": "bronze",
    "name": "Test Repo Grep",
    "notes": "",
    "owner": "platform"
  }
}
$ go run main.go get check Z2lkOi8vb3BzbGV2ZWwvQ2hlY2tzOjpSZXBvRmlsZS8xODQz        
{
  "Version": "1",
  "Kind": "repo_file",
  "Spec": {
    "category": "security",
    "directorySearch": false,
    "enabled": true,
    "fileContentsPredicate": {
      "Type": "equals",
      "Value": "postgres"
    },
    "filePaths": [
      "/src",
      "/test"
    ],
    "filter": "test-filter",
    "level": "silver",
    "name": "Hello World",
    "notes": "",
    "owner": "platform"
  }
}
```

**Review by rocktavious — APPROVED** [review]
Thanks for fixing a non-related bug

**Pull request merged**
